export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED';


export const GET_INGREDIENTS_FOR_CONSTRUCTOR = 'GET_INGREDIENTS_FOR_CONSTRUCTOR';
export const SET_INGREDIENTS_FOR_CONSTRUCTOR = 'SET_INGREDIENTS_FOR_CONSTRUCTOR';
export const REMOVE_INGREDIENTS_FOR_CONSTRUCTOR = 'REMOVE_INGREDIENTS_FOR_CONSTRUCTOR';


export const SET_INGREDIENT_DETAIL = 'GET_INGREDIENT_DETAIL';
export const RESET_INGREDIENT_DETAIL = 'RESET_INGREDIENT_DETAIL';

export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILED = 'GET_ORDER_FAILED';

export const ADD_INGREDIENT_COUNT = 'ADD_INGREDIENT_COUNT';
export const REMOVE_INGREDIENT_COUNT = 'REMOVE_INGREDIENT_COUNT';

export const CHANGE_BUN = 'CHANGE_BUN';
export const ADD_ORDER_PRICE = 'ADD_ORDER_PRICE';
export const REMOVE_ORDER_PRICE = 'REMOVE_ORDER_PRICE';

export const SORT_CONSTRUCTOR_ITEMS = 'SORT_CONSTRUCTOR_ITEMS';

export const RECOVERY_PASSWORD_REQUEST = "RECOVERY_PASSWORD_REQUEST";
export const RECOVERY_PASSWORD_SUCCESS = "RECOVERY_PASSWORD_SUCCESS";
export const RECOVERY_PASSWORD_FAILED = "RECOVERY_PASSWORD_FAILED";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const SET_USER = "SET_USER";

export const REGISTRATION_REQUEST = "REGISTRATION_REQUEST";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";